### ISSUE TITLE
Missing "-d" option for sqlcmd

### ISSUE THREAD

**Issue by gamissah** [cagrin/sqlcmd-arm64#1]
Hi, I recently used your https://github.com/cagrin/azure-sql-edge-arm64 and realised I can't add the '-d' option for the sqlcmd. I get this error if I use it
<img width="656" alt="Screenshot 2022-07-23 at 4 58 23 PM" src="https://user-images.githubusercontent.com/12752087/180615138-f57095b1-45d3-4a34-a3fe-e4d25efb47fc.png">

So I tracked the issue back to this repo, where it's missing the '-d' in the source code file
<img width="1056" alt="Screenshot 2022-07-23 at 4 59 46 PM" src="https://user-images.githubusercontent.com/12752087/180615222-c644505a-f448-4dd0-915c-446f81edebcb.png">

Anyways just wanted to call this out. Hope it gets fixed soon. Thanks.

**Comment by cagrin** [comment]
[gamissah](https://github.com/gamissah) thanks for reporting this. I also updated **azure-sql-edge-arm64** at Docker Hub.

BTW: I wonder what is your use case of this azure-sql-edge-arm64 docker image? I use it specially when running unit tests inside DotNet.Testcontainers on M1 Mac.

**Comment by gamissah** [comment]
> 
@cagrin 
Thanks for fixing it. Am using the **azure-sql-edge-arm64** because I recently upgraded to Apple Silicon laptop and my **mssql/server**  development container failed to run. So I had to look for alternatives that works with M1 chips and also should be compatible with my existing app containers that connects to the db server.
